# Generated by Django 3.2 on 2021-05-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0004_auto_20210505_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, choices=[('Diamonds', 'Diamonds'), ('Pierres', 'Pierres'), ('Metal', 'Metal'), ('Or Blanc', 'Or Blanc')], max_length=50, null=True),
        ),
    ]
